# Generated by Django 4.2.1 on 2023-06-10 11:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="gallery",
            name="created_date",
        ),
        migrations.RemoveField(
            model_name="gallery",
            name="description",
        ),
        migrations.AlterField(
            model_name="gallery",
            name="cover_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="galleries/covers"
            ),
        ),
        migrations.AlterField(
            model_name="gallery",
            name="title",
            field=models.CharField(max_length=200),
        ),
    ]
