# Generated by Django 4.2.1 on 2023-06-10 12:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0002_remove_gallery_created_date_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="image",
            name="description",
        ),
        migrations.RemoveField(
            model_name="image",
            name="uploaded_date",
        ),
    ]
